import{a as w,S as L,i as d}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();let a=1,p=40,i,m="";function v(){a=1}function S(o){m=o}function q(){a+=1}const P="48843638-b89903974de20d086a3125d9e",k="https://pixabay.com/api/";async function h(o,r){try{const e=await w.get(k,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:p}});return i=Math.ceil(e.data.totalHits/p),e.data.hits}catch(e){return console.error("Error fetching images:",e),[]}}const g=document.querySelector(".gallery"),$=new L(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!1,animationSlide:!0});function b(o){if(o.length===0){d.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please, try again!"}),g.innerHTML="";return}const r=o.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="gallery-stats">
          <p>Likes <span>${e.likes}</span></p>
          <p>Views <span>${e.views}</span></p>
          <p>Comments <span>${e.comments}</span></p>
          <p>Downloads <span>${e.downloads}</span></p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),$.refresh()}const C=document.querySelector(".form"),f=document.querySelector(".input"),u=document.querySelector(".loader"),I=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn");n.style.display="none";const y=document.querySelector(".loader-more");y.style.display="none";function M(){I.innerHTML=""}C.addEventListener("submit",async o=>{o.preventDefault();const r=f.value.trim();if(r===""){d.show({message:"Please enter a search query",position:"topRight",backgroundColor:"red"});return}u.style.display="block",M(),v(),S(r),f.value="",n.style.display="none";try{const e=await h(r);b(e),u.style.display="none",a<i&&(n.style.display="block")}catch(e){console.log(e)}});n.addEventListener("click",async o=>{var r;o.preventDefault(),n.style.display="none",y.style.display="block";try{q();const e=await h(m,a);b(e);const l=(r=document.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height;l&&window.scrollBy({top:2*l,behavior:"smooth"}),y.style.display="none",a>=i?(d.show({position:"topRight",backgroundColor:"red",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none"):a<i&&(n.style.display="block")}catch(e){console.log(e),u.style.display="none"}});
//# sourceMappingURL=index.js.map
