import{S as w,i as u,a as L}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=e(t);fetch(t.href,a)}})();const d=document.querySelector(".gallery"),v=new w(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!1,animationSlide:!0});function f(o){if(o.length===0){u.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please, try again!"}),d.innerHTML="";return}const r=o.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="gallery-stats">
          <p>Likes <span>${e.likes}</span></p>
          <p>Views <span>${e.views}</span></p>
          <p>Comments <span>${e.comments}</span></p>
          <p>Downloads <span>${e.downloads}</span></p>
        </div>
      </li>`).join("");d.insertAdjacentHTML("beforeend",r),v.refresh()}const c=document.querySelector(".load-more-btn");c.style.display="none";let n=1,p=40,l,h="";function S(){n=1}function q(o){h=o}const $="48843638-b89903974de20d086a3125d9e",P="https://pixabay.com/api/";async function b(o,r){try{const e=await L.get(P,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:p}});return l=Math.ceil(e.data.totalHits/p),e.data.hits}catch(e){return console.error("Error fetching images:",e),[]}}c.addEventListener("click",async o=>{var r;if(o.preventDefault(),console.log(`Clicked! Current page: ${n}, Total pages: ${l}`),n>=l){u.show({position:"topRight",backgroundColor:"red",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none";return}try{const e=await b(h,n);f(e),n+=1;const s=(r=document.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height;s&&window.scrollBy({top:2*s,behavior:"smooth"})}catch(e){console.log(e)}finally{loader.style.display="none"}});const C=document.querySelector(".form"),y=document.querySelector(".input"),g=document.querySelector(".loader"),k=document.querySelector(".gallery"),m=document.querySelector(".load-more-btn");function I(){k.innerHTML=""}C.addEventListener("submit",async o=>{o.preventDefault();const r=y.value.trim();if(r===""){u.show({message:"Please enter a search query",position:"topRight",backgroundColor:"red"});return}g.style.display="block",I(),S(),q(r),y.value="",m.style.display="none";try{const e=await b(r);setTimeout(()=>{f(e),g.style.display="none",n<l&&(m.style.display="block")},1e3)}catch(e){console.log(e)}});
//# sourceMappingURL=index.js.map
