import{S as L,i as d,a as S}from"./assets/vendor-BDaiwwc1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const y=document.querySelector(".gallery"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!1,animationSlide:!0});function h(r){if(r.length===0){d.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please, try again!"}),y.innerHTML="";return}const o=r.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="gallery-stats">
          <p>Likes <span>${e.likes}</span></p>
          <p>Views <span>${e.views}</span></p>
          <p>Comments <span>${e.comments}</span></p>
          <p>Downloads <span>${e.downloads}</span></p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),q.refresh()}const u=document.querySelector(".loader-more"),l=document.querySelector(".load-more-btn");l.style.display="none";u.style.display="none";let n=1,p=40,i,b="";function v(){n=1}function P(r){b=r}const $="48843638-b89903974de20d086a3125d9e",k="https://pixabay.com/api/";async function w(r,o){try{const e=await S.get(k,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:p}});return i=Math.ceil(e.data.totalHits/p),e.data.hits}catch(e){return console.error("Error fetching images:",e),[]}}l.addEventListener("click",async r=>{if(r.preventDefault(),n>=i){d.show({position:"topRight",backgroundColor:"red",message:"We're sorry, but you've reached the end of search results."}),l.style.display="none";return}l.style.display="none",u.style.display="block",setTimeout(async()=>{var o;try{const e=await w(b,n);h(e),n+=1;const a=(o=document.querySelector(".gallery-item"))==null?void 0:o.getBoundingClientRect().height;a&&window.scrollBy({top:2*a,behavior:"smooth"}),u.style.display="none",n<i&&(l.style.display="block")}catch(e){console.log(e),loader.style.display="none"}},2e3)});const M=document.querySelector(".form"),m=document.querySelector(".input"),g=document.querySelector(".loader"),C=document.querySelector(".gallery"),f=document.querySelector(".load-more-btn");function I(){C.innerHTML=""}M.addEventListener("submit",async r=>{r.preventDefault();const o=m.value.trim();if(o===""){d.show({message:"Please enter a search query",position:"topRight",backgroundColor:"red"});return}g.style.display="block",I(),v(),P(o),m.value="",f.style.display="none";try{const e=await w(o);setTimeout(()=>{h(e),g.style.display="none",n<i&&(f.style.display="block")},1e3)}catch(e){console.log(e)}});
//# sourceMappingURL=index.js.map
